// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t *ui_Screen1 = NULL;lv_obj_t *ui_Label1 = NULL;lv_obj_t *ui_Slider1 = NULL;lv_obj_t *ui_Checkbox1 = NULL;lv_obj_t *ui_Switch1 = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label1 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"Hello World!");
lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_36, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Slider1 = lv_slider_create(ui_Screen1);
lv_slider_set_value( ui_Slider1, 0, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_Slider1)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_Slider1, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_Slider1, 224);
lv_obj_set_height( ui_Slider1, 26);
lv_obj_set_x( ui_Slider1, 22 );
lv_obj_set_y( ui_Slider1, -87 );
lv_obj_set_align( ui_Slider1, LV_ALIGN_CENTER );

ui_Checkbox1 = lv_checkbox_create(ui_Screen1);
lv_obj_set_width( ui_Checkbox1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Checkbox1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Checkbox1, -3 );
lv_obj_set_y( ui_Checkbox1, 71 );
lv_obj_set_align( ui_Checkbox1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Checkbox1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_set_style_text_font(ui_Checkbox1, &lv_font_montserrat_30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Switch1 = lv_switch_create(ui_Screen1);
lv_obj_set_width( ui_Switch1, 74);
lv_obj_set_height( ui_Switch1, 25);
lv_obj_set_x( ui_Switch1, 4 );
lv_obj_set_y( ui_Switch1, 137 );
lv_obj_set_align( ui_Switch1, LV_ALIGN_CENTER );

}

void ui_Screen1_screen_destroy(void)
{
   if (ui_Screen1) lv_obj_del(ui_Screen1);

// NULL screen variables
ui_Screen1= NULL;
ui_Label1= NULL;
ui_Slider1= NULL;
ui_Checkbox1= NULL;
ui_Switch1= NULL;

}
